"""membuat tabel dosen

Revision ID: c08991da0885
Revises: 1ab9f73b3a6a
Create Date: 2021-12-09 14:36:02.936318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c08991da0885'
down_revision = '1ab9f73b3a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosen', sa.Column('alamat', sa.String(length=100), nullable=False))
    op.drop_column('dosen', 'almaat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosen', sa.Column('almaat', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('dosen', 'alamat')
    # ### end Alembic commands ###
